namespace StackMachineBuilder {
	template struct BindCPANEQ<int>;
	template struct BindCPANEQ<char>;
	template struct BindCPANEQ<double>;
	template struct BindCPANEQ<bool>;
	template struct BindCPAEQ<int>;
	template struct BindCPAEQ<char>;
	template struct BindCPAEQ<double>;
	template struct BindCPAEQ<bool>;
	template struct BindDREF<int>;
	template struct BindDREF<char>;
	template struct BindDREF<double>;
	template struct BindDREF<bool>;
	template struct BindDREF<void*>;
	template struct BindPOP<int>;
	template struct BindPOP<char>;
	template struct BindPOP<double>;
	template struct BindPOP<bool>;
	template struct BindPOP<void*>;
	template struct BindPUSH<int>;
	template struct BindPUSH<char>;
	template struct BindPUSH<double>;
	template struct BindPUSH<bool>;
	template struct BindPUSH<void*>;
	template struct BindLDR<int>;
	template struct BindLDR<char>;
	template struct BindLDR<double>;
	template struct BindLDR<bool>;
	template struct BindLD<int>;
	template struct BindLD<char>;
	template struct BindLD<double>;
	template struct BindLD<bool>;
	template struct BindSCAN<int>;
	template struct BindSCAN<char>;
	template struct BindSCAN<double>;
	template struct BindSCAN<bool>;
	template struct BindPRINT<int>;
	template struct BindPRINT<char>;
	template struct BindPRINT<double>;
	template struct BindPRINT<bool>;
	template struct BindINC<int>;
	template struct BindINC<char>;
	template struct BindINC<double>;
	template struct BindADD<int>;
	template struct BindADD<char>;
	template struct BindADD<bool>;
	template struct BindADD<double>;
	template struct BindAND<int>;
	template struct BindAND<char>;
	template struct BindAND<bool>;
	template struct BindOR<int>;
	template struct BindOR<char>;
	template struct BindOR<bool>;
	template struct BindXOR<int>;
	template struct BindXOR<char>;
	template struct BindXOR<bool>;
	template struct BindNOT<int>;
	template struct BindNOT<char>;
	template struct BindNOT<bool>;
	template struct BindCAST<int, double>;
	template struct BindCAST<double, int>;
	template struct BindCAST<int, char>;
	template struct BindCAST<char, int>;
	template struct BindCAST<int, bool>;
	template struct BindCAST<bool, int>;
	template struct BindCAST<double, char>;
	template struct BindCAST<char, double>;
	template struct BindCAST<double, bool>;
	template struct BindCAST<bool, double>;
	template struct BindCAST<char, bool>;
	template struct BindCAST<bool, char>;
}